# -*- coding: utf-8 -*-
"""ConfidenceAsManifoldStability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186SS_VARdB2ynV1xozHfzPC9c-McS3iB
"""

from one.api import ONE
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

one = ONE(
    base_url='https://openalyx.internationalbrainlab.org',
    silent=True
)

def trials_to_df(trials):
    """
    Convert IBL trials object to a pandas DataFrame
    using only 1-D trial-wise fields.
    """
    data = {}
    for k, v in trials.items():
        if hasattr(v, 'ndim') and v.ndim == 1:
            data[k] = v
    return pd.DataFrame(data)

eids = [
    'e2b845a1-e313-4a08-bc61-a5f662ed295e',
    # add more EIDs here
]

results = {}

for eid in eids:
    print(f'\nAnalyzing EID: {eid}')
    eid_result = {}

    # ---- Session metadata ----
    details = one.get_details(eid)
    eid_result['subject'] = details.get('subject')
    eid_result['date'] = details.get('date')
    eid_result['lab'] = details.get('lab')

    # ---- Behavioral data ----
    trials = one.load_object(eid, 'trials', revision='latest')
    trials_df = trials_to_df(trials)

    eid_result['n_trials'] = len(trials_df)

    # Signed contrast
    trials_df['signed_contrast'] = (
        trials_df['contrastRight'].fillna(0)
        - trials_df['contrastLeft'].fillna(0)
    )

    # reaction time definition
    trials_df['reaction_time'] = (
        trials_df['response_times'] - trials_df['goCue_times']
    )

    accuracy = np.mean(trials_df['feedbackType'] == 1)
    median_rt = np.nanmedian(trials_df['reaction_time'])

    eid_result['behavior'] = {
        'accuracy': float(accuracy),
        'median_rt': float(median_rt)
    }

    # ---- Probe insertions ----
    insertions = one.alyx.rest('insertions', 'list', session=eid)
    eid_result['n_probes'] = len(insertions)
    eid_result['pids'] = [ins['id'] for ins in insertions]

    results[eid] = eid_result

results

def get_valid_trials(trials_df):
    valid = (
        (trials_df['choice'] != 0) &
        (trials_df['feedbackType'].isin([1, -1])) &
        (trials_df['reaction_time'] > 0) &
        np.isfinite(trials_df['reaction_time'])
    )
    return trials_df[valid].reset_index(drop=True)

trials_df = get_valid_trials(trials_df)

rt_median = np.nanmedian(trials_df['reaction_time'])

trials_df['confidence'] = np.where(
    trials_df['reaction_time'] <= rt_median,
    'high',
    'low'
)

datasets = one.list_datasets(eid, filename='spikes.times.npy')

collections = sorted({
    Path(ds).parent.as_posix()
    for ds in datasets
})

print(collections)

if len(collections) == 0:
    print('No neural data for this EID')
else:
    for collection in collections:
        print(f'Loading {collection}')

        spikes = one.load_object(
            eid,
            'spikes',
            collection=collection,
            revision='latest'
        )

        clusters = one.load_object(
            eid,
            'clusters',
            collection=collection,
            revision='latest'
        )

        print(f'  spikes: {len(spikes["times"])}')
        print(f'  clusters: {len(np.unique(spikes["clusters"]))}')

# Alignment parameters
t_before = 0.5
t_after = 1.0
bin_size = 0.02  # 20 ms

bins = np.arange(-t_before, t_after + bin_size, bin_size)
bin_centers = (bins[:-1] + bins[1:]) / 2

def build_population_matrix(spikes, trials_df, bins):
    """
    Returns:
    X: (n_trials, n_neurons, n_timebins)
    neuron_ids: array of cluster ids
    """

    spike_times = spikes['times']
    spike_clusters = spikes['clusters']

    neuron_ids = np.unique(spike_clusters)
    n_trials = len(trials_df)
    n_neurons = len(neuron_ids)
    n_bins = len(bins) - 1

    X = np.zeros((n_trials, n_neurons, n_bins), dtype=np.float32)

    align_times = trials_df['stimOn_times'].values

    for ti, t0 in enumerate(align_times):
        t_start = t0 + bins[0]
        t_end = t0 + bins[-1]

        mask = (spike_times >= t_start) & (spike_times < t_end)
        st = spike_times[mask] - t0
        sc = spike_clusters[mask]

        for ni, cid in enumerate(neuron_ids):
            neuron_spikes = st[sc == cid]
            X[ti, ni, :] = np.histogram(neuron_spikes, bins=bins)[0]

    return X, neuron_ids

population_data = {}

for collection in collections:
    print(f'Building population matrix for {collection}')

    spikes = one.load_object(eid, 'spikes', collection=collection, revision='latest')

    X, neuron_ids = build_population_matrix(spikes, trials_df, bins)

    population_data[collection] = {
        'X': X,
        'neurons': neuron_ids
    }

    print('  Shape:', X.shape)

def compute_neural_manifold(X, n_components=6):
    """
    X: (trials, neurons, time)
    Returns:
    Z: (trials, time, components)
    pca: fitted PCA object
    """

    n_trials, n_neurons, n_time = X.shape

    # Flatten trials × time
    X_flat = X.transpose(0, 2, 1).reshape(-1, n_neurons)

    # Z-score neurons
    X_flat = StandardScaler().fit_transform(X_flat)

    pca = PCA(n_components=n_components)
    Z_flat = pca.fit_transform(X_flat)

    # Restore shape
    Z = Z_flat.reshape(n_trials, n_time, n_components)

    return Z, pca

manifolds = {}

for collection, pdata in population_data.items():
    X = pdata['X']

    Z, pca = compute_neural_manifold(X)

    manifolds[collection] = {
        'Z': Z,
        'pca': pca
    }

    print(f'{collection}: explained variance:',
          np.sum(pca.explained_variance_ratio_[:3]))

correct = trials_df['feedbackType'] == 1
incorrect = trials_df['feedbackType'] == -1

def mean_trajectory(Z, mask):
    return Z[mask].mean(axis=0)  # (time, components)

for collection, data in manifolds.items():
    Z = data['Z']

    traj_correct = mean_trajectory(Z, correct)
    traj_incorrect = mean_trajectory(Z, incorrect)

    dist = np.linalg.norm(traj_correct - traj_incorrect, axis=1)

    print(f'{collection} mean traj separation:', dist.mean())

high_ev = np.abs(trials_df['signed_contrast']) >= 0.25
low_ev  = np.abs(trials_df['signed_contrast']) < 0.25

def trajectory_dispersion(Z):
    """
    Z: (trials, time, components)
    Returns:
    dispersion: (time,)
    """
    mean_traj = Z.mean(axis=0)
    dist = np.linalg.norm(Z - mean_traj, axis=2)
    return dist.mean(axis=0)

confidence_results = {}

for collection, data in manifolds.items():
    Z = data['Z']

    conf = {}

    conf['correct'] = trajectory_dispersion(Z[correct])
    conf['incorrect'] = trajectory_dispersion(Z[incorrect])

    conf['high_ev'] = trajectory_dispersion(Z[high_ev])
    conf['low_ev']  = trajectory_dispersion(Z[low_ev])

    confidence_results[collection] = conf

post_stim = bin_centers > 0

def scalar_confidence(dispersion):
    return dispersion[post_stim].mean()

for collection, conf in confidence_results.items():
    print(f'\n{collection}')

    print('  Correct:', scalar_confidence(conf['correct']))
    print('  Incorrect:', scalar_confidence(conf['incorrect']))

    print('  High evidence:', scalar_confidence(conf['high_ev']))
    print('  Low evidence:', scalar_confidence(conf['low_ev']))

for collection, conf in confidence_results.items():
    plt.figure(figsize=(6,4))

    plt.plot(bin_centers, conf['high_ev'], label='High evidence')
    plt.plot(bin_centers, conf['low_ev'], label='Low evidence')

    plt.axvline(0, linestyle='--')
    plt.xlabel('Time from stimulus (s)')
    plt.ylabel('Trajectory dispersion')
    plt.title(collection)
    plt.legend()
    plt.show()

















